// This source code was generated by dclangen
module libclang.cxerrorcode;
enum CXErrorCode
{
    _Success = 0x0,
    _Failure = 0x1,
    _Crashed = 0x2,
    _InvalidArguments = 0x3,
    _ASTReadError = 0x4,
}
